pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "Budget"
include ':app'
include ':uikit'
include ':features'
include ':features:auth'
include ':common'
include ':features:bottom-navigation'
include ':features:bottom-navigation:host'
include ':features:bottom-navigation:home'
include ':features:bottom-navigation:statistic'
include ':features:create-update-wallet'
include ':features:splash'
include ':features:create-udate-category'
