plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-android'
    id 'kotlin-kapt'
    id 'com.google.dagger.hilt.android'
}

android {
    namespace 'ru.bysoft.android.budget.features.currency_rates'
    compileSdk compile_sdk

    defaultConfig {
        minSdk min_sdk
        targetSdk target_sdk

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    composeOptions {
        kotlinCompilerExtensionVersion compose_compiler_version
    }
    buildFeatures{
        compose true
    }
    kapt {
        correctErrorTypes true
    }
}

dependencies {
    implementation "androidx.core:core-ktx:$core_ktx_version"

    //hilt
    implementation "com.google.dagger:hilt-android:$hilt_version"
    kapt "com.google.dagger:hilt-compiler:$hilt_version"
    implementation "androidx.hilt:hilt-navigation-compose:$hilt_compiller_version"
    kapt "androidx.hilt:hilt-compiler:$hilt_compiller_version"
    annotationProcessor "androidx.hilt:hilt-compiler:$hilt_compiller_version"

    implementation "androidx.room:room-runtime:$room_version"
    annotationProcessor "androidx.room:room-compiler:$room_version"
    annotationProcessor "android.arch.persistence.room:compiler:1.1.1"
    kapt "androidx.room:room-compiler:$room_version"

    implementation project(path: ':api')
    implementation project(':common')
    implementation project(':currency')
}